name       : haskell-text-icu
version    : 0.7.0.1
release    : 12
source     :
    - https://hackage.haskell.org/package/text-icu-0.7.0.1/text-icu-0.7.0.1.tar.gz : e2764c2749033706eed5b9fb3cda11177ad15cdf11912028f551eca39a2c7f78
license    : BSD-2-Clause
component  : programming.haskell
summary    : This package provides the Data.Text.ICU library, for performing complex manipulation of Unicode text.
description: |
    This package provides the Data.Text.ICU library, for performing complex manipulation of Unicode text.
networking : yes
builddeps  :
    - pkgconfig(icu-i18n)
    - ghc-devel
    - haskell-cabal-install
rundeps    :
    - devel :
        - ghc-devel
        - libicu-devel
setup      : |
    %patch -p1 < $pkgfiles/icu68.patch
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
